# Generated by Django 5.0.6 on 2024-06-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjjorganizer', '0003_tournament_tournamenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='started',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
