# Generated by Django 5.0.6 on 2024-06-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjjorganizer', '0004_tournament_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
