# Generated by Django 5.0.6 on 2024-06-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjjorganizer', '0005_alter_tournament_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='tournament',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='bjjorganizer.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournamentType',
            field=models.CharField(choices=[('freeforall', 'Free for All')], max_length=100),
        ),
    ]
