# Generated by Django 5.0.6 on 2024-06-10 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjjorganizer', '0006_alter_competitor_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='bjjorganizer.tournament'),
        ),
    ]
