# Generated by Django 5.0.6 on 2024-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjjorganizer', '0007_alter_competitor_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='tournament',
        ),
        migrations.AddField(
            model_name='competitor',
            name='tournaments',
            field=models.ManyToManyField(blank=True, null=True, related_name='competitors', to='bjjorganizer.tournament'),
        ),
    ]
